In [1]:
import torch
from torch import nn
from torch.nn import functional as F
class F1_Loss(nn.Module):

    def __init__(self, num_classes = -1 , weights = 1, epsilon=1e-7):
        super().__init__()
        self.weights = weights 
        self.epsilon = epsilon
        self.num_classes = num_classes
        
    def forward(self, y_pred, y_true,):
        assert y_pred.ndim == 2
        assert y_true.ndim == 1
        y_true = F.one_hot(y_true, self.num_classes).to(torch.float32)
        y_pred = F.softmax(y_pred, dim=1)
        
        tp = (y_true * y_pred).sum(dim=0).to(torch.float32)
        tn = ((1 - y_true) * (1 - y_pred)).sum(dim=0).to(torch.float32)
        fp = ((1 - y_true) * y_pred).sum(dim=0).to(torch.float32)
        fn = (y_true * (1 - y_pred)).sum(dim=0).to(torch.float32)

        precision = tp / (tp + fp + self.epsilon)
        recall = tp / (tp + fn + self.epsilon)

        f1 = 2* (precision*recall) / (precision + recall + self.epsilon)
        f1 = f1.clamp(min=self.epsilon, max=1-self.epsilon)
        return 1 - (f1*self.weights).sum()


/home/prsood/projects/def-whkchun/prsood/sarcasm_venv/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [1]:
class F1_Loss(nn.Module):

    def __init__(self, num_classes = -1 , weights = 1, epsilon=1e-7):
        super().__init__()
        self.weights = weights 
        self.epsilon = epsilon
        self.num_classes = num_classes
        
    def forward(self, y_pred, y_true,):
        assert y_pred.ndim == 2
        assert y_true.ndim == 1
        y_true = F.one_hot(y_true, self.num_classes).to(torch.float32)
        y_pred = F.softmax(y_pred, dim=1)
        
        tp = (y_true * y_pred).sum(dim=0).to(torch.float32)
        tn = ((1 - y_true) * (1 - y_pred)).sum(dim=0).to(torch.float32)
        fp = ((1 - y_true) * y_pred).sum(dim=0).to(torch.float32)
        fn = (y_true * (1 - y_pred)).sum(dim=0).to(torch.float32)

        precision = tp / (tp + fp + self.epsilon)
        recall = tp / (tp + fn + self.epsilon)

        f1 = 2* (precision*recall) / (precision + recall + self.epsilon)
        f1 = f1.clamp(min=self.epsilon, max=1-self.epsilon)
        return 1 - (f1*self.weights).sum()


NameError: name 'nn' is not defined

In [4]:
truth = torch.Tensor([0 , 1 , 2 , 2 , 3])
preds = torch.rand((5,4))

In [5]:
epsilon = 1e-7
y_pred = preds
y_true = truth
assert y_pred.ndim == 2
assert y_true.ndim == 1


In [6]:
y_true = F.one_hot(y_true, num_classes = 4).to(torch.float32)
y_pred = F.softmax(y_pred, dim=1)

: 

: 

In [8]:
# preds.argmax(dim = 1)

tensor([0, 2, 2, 0, 3])

In [5]:
truth.ndim

1

In [6]:
loss = F1_Loss()

In [8]:
loss(preds , truth).item()

1.1920928955078125e-07

In [17]:
from torchmetrics.classification import MulticlassConfusionMatrix
confusionMatrix = MulticlassConfusionMatrix( num_classes = 4 , ignore_index=None , normalize='none' , validate_args=False)

In [18]:
confusionMatrix.reset()
confusionMatrix.update(preds , truth)
conf = confusionMatrix.compute()
conf

tensor([[0, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 1, 1, 0],
        [0, 0, 0, 1]])

In [9]:
epsilon = 1e-7
y_pred = preds
y_true = truth
tp = (y_true * y_pred).sum(dim=0).to(torch.float32)
tn = ((1 - y_true) * (1 - y_pred)).sum(dim=0).to(torch.float32)
fp = ((1 - y_true) * y_pred).sum(dim=0).to(torch.float32)
fn = (y_true * (1 - y_pred)).sum(dim=0).to(torch.float32)
tp,tn,fp,fn

(tensor(18.), tensor(5.), tensor(-8.), tensor(-10.))

In [ ]:
precision = tp / (tp + fp + epsilon)
recall = tp / (tp + fn + epsilon)

precision,recall

In [ ]:
# f1 = 2* (precision*recall) / (precision + recall + self.epsilon)
# f1 = f1.clamp(min=self.epsilon, max=1-self.epsilon)

In [11]:
x = torch.Tensor([0.5045, 0.8234, 0.8744, 0.8764, 0.9212])
x_norm = x / x.sum()
x_norm , x_norm.sum().item()

(tensor([0.1261, 0.2059, 0.2186, 0.2191, 0.2303]), 1.0)

In [12]:
x[0] -= 0.2
x[1:] += .05
x

tensor([0.3045, 0.8734, 0.9244, 0.9264, 0.9712])

In [13]:
x_new_norm = x/x.sum()
x_new_norm , x_new_norm.sum().item()

(tensor([0.0761, 0.2184, 0.2311, 0.2316, 0.2428]), 1.0)