In [1]:
import pandas as pd
import torchaudio
import torch
import numpy as np
from torch.nn.utils.rnn import pad_sequence
from transformers import  AutoProcessor 


/home/prsood/projects/def-whkchun/prsood/sarcasm_venv/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
df = pd.read_pickle("/project/def-whkchun/prsood/multi-modal-emotion/data/text_audio_video_emotion_data.pkl")

In [3]:
audio_path1 = "../data/train_splits_wav/dia71_utt0.wav"

# audio_path2 = "../data/val_splits_wav/dia113_utt9.wav"

def speech_file_to_array_fn(path , target_sampling_rate = 16000):
    speech_array, sampling_rate = torchaudio.load(path)
    resampler = torchaudio.transforms.Resample(sampling_rate, target_sampling_rate)
    speech = resampler(speech_array).squeeze()
    return torch.mean(speech, dim=0) if len(speech.shape) > 1 else speech # over the channel dimension

In [4]:
PROC = AutoProcessor.from_pretrained("audeering/wav2vec2-large-robust-12-ft-emotion-msp-dim")
speech_list = [speech_file_to_array_fn(audio_path1)]
numpy_speech_list = [item.numpy() for item in speech_list] 

speech_list_mask = torch.Tensor(np.array(PROC( numpy_speech_list, sampling_rate = 16000 , padding = True)['attention_mask']))
speech_list_input_values = pad_sequence(speech_list , batch_first = True, padding_value=0)


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [5]:
speech_list_mask , speech_list_mask.shape

(tensor([[1., 1., 1.,  ..., 1., 1., 1.]]), torch.Size([1, 1024]))

In [15]:
speech_list[1].shape

torch.Size([17408])

In [11]:
(speech_list_mask[0] == 0).nonzero(as_tuple=True)[0] , (speech_list_mask[1] == 0).nonzero(as_tuple=True)[0]

(tensor([], dtype=torch.int64),
 tensor([17408, 17409, 17410,  ..., 24232, 24233, 24234]))

In [10]:
speech_list_input_values , speech_list_input_values.shape

(tensor([[ 0.0206,  0.0559,  0.0851,  ...,  0.0000,  0.0000,  0.0000],
         [-0.0044, -0.0066, -0.0075,  ...,  0.0000,  0.0000,  0.0000]]),
 torch.Size([2, 24235]))

In [6]:
# df_train = df[df["split"] == "train"]
df.sort_values(by=['audio_shape'], ascending=True)

emotion  dialog  utterance  \
6282         1     406          2   
7384         1     523         10   
13456        3     108          5   
5666         0     332          1   
4220         0     179          8   
...        ...     ...        ...   
9542         1     748          0   
8626         2     649          0   
7341         1     517          6   
13141        0      74          7   
13153        3      74         19   

                                                    text  num_words  split  \
6282                                      hey , pheebs !          4  train   
7384                                         hi pheebs !          3  train   
13456                                               ow !          2    val   
5666                                                 shh          1  train   
4220                                       sagittarius ?          2  train   
...                                                  ...        ...    ...   
9542   oh yes ! thank you very much ! oh that s that ...         19  train   
8626   joey ? could you get that ? what are you doing...         21  train   
7341   yeah , say my name say it ! and now i m going ...         27  train   
13141  okay uh , ross and rachel rachel and ross that...         22    val   
13153  i m pregnant ross ? ross ? okay , whenever you...         25    val   

                                         audio_path          name  \
6282    ../../data/train_splits_wav/dia406_utt2.wav   dia406_utt2   
7384   ../../data/train_splits_wav/dia523_utt10.wav  dia523_utt10   
13456     ../../data/val_splits_wav/dia108_utt5.wav   dia108_utt5   
5666    ../../data/train_splits_wav/dia332_utt1.wav   dia332_utt1   
4220    ../../data/train_splits_wav/dia179_utt8.wav   dia179_utt8   
...                                             ...           ...   
9542    ../../data/train_splits_wav/dia748_utt0.wav   dia748_utt0   
8626    ../../data/train_splits_wav/dia649_utt0.wav   dia649_utt0   
7341    ../../data/train_splits_wav/dia517_utt6.wav   dia517_utt6   
13141      ../../data/val_splits_wav/dia74_utt7.wav    dia74_utt7   
13153     ../../data/val_splits_wav/dia74_utt19.wav   dia74_utt19   

      emotion_label  num_channels  audio_shape  size_padding  \
6282            joy             6         1024          6144   
7384            joy             6         1024          6144   
13456         anger             6         1024          6144   
5666        neutral             2         1024          2048   
4220        neutral             6         1024          6144   
...             ...           ...          ...           ...   
9542            joy             2       257024        514048   
8626       surprise             2       281259        562518   
7341            joy             2       322219        644438   
13141       neutral             2       335872        671744   
13153         anger             2       456704        913408   

                                    video_path sentiment_label  sentiment  \
6282    ../../data/train_video/dia406_utt2.mp4        positive          2   
7384   ../../data/train_video/dia523_utt10.mp4        positive          2   
13456     ../../data/val_video/dia108_utt5.mp4        negative          0   
5666    ../../data/train_video/dia332_utt1.mp4         neutral          1   
4220    ../../data/train_video/dia179_utt8.mp4         neutral          1   
...                                        ...             ...        ...   
9542    ../../data/train_video/dia748_utt0.mp4        positive          2   
8626    ../../data/train_video/dia649_utt0.mp4        positive          2   
7341    ../../data/train_video/dia517_utt6.mp4        positive          2   
13141      ../../data/val_video/dia74_utt7.mp4         neutral          1   
13153     ../../data/val_video/dia74_utt19.mp4        negative          0   

                                         timings  
6282                                        None  


emotion  dialog  utterance  \
1578         0     169         16   
2153         3     234          5   
4219         0     179          7   
4216         0     179          4   
10400        4     841          6   
...        ...     ...        ...   
13398        2      99          3   
5666         0     332          1   
3293         0      71          0   
7384         1     523         10   
5484         3     312          9   

                                                    text  num_words  split  \
1578                                                yeah          1   test   
2153   you were gonna spill hot coffee all over me , ...         14   test   
4219                                                nope          1  train   
4216                                            taurus ?          2  train   
10400                                       right here !          3  train   
...                                                  ...        ...    ...   
13398                                        ooohhhh ! !          3    val   
5666                                                 shh          1  train   
3293                                            pheebs ?          2  train   
7384                                         hi pheebs !          3  train   
5484                                               noo !          2  train   

                                         audio_path          name  \
1578    ../../data/test_splits_wav/dia169_utt16.wav  dia169_utt16   
2153     ../../data/test_splits_wav/dia234_utt5.wav   dia234_utt5   
4219    ../../data/train_splits_wav/dia179_utt7.wav   dia179_utt7   
4216    ../../data/train_splits_wav/dia179_utt4.wav   dia179_utt4   
10400   ../../data/train_splits_wav/dia841_utt6.wav   dia841_utt6   
...                                             ...           ...   
13398      ../../data/val_splits_wav/dia99_utt3.wav    dia99_utt3   
5666    ../../data/train_splits_wav/dia332_utt1.wav   dia332_utt1   
3293     ../../data/train_splits_wav/dia71_utt0.wav    dia71_utt0   
7384   ../../data/train_splits_wav/dia523_utt10.wav  dia523_utt10   
5484    ../../data/train_splits_wav/dia312_utt9.wav   dia312_utt9   

      emotion_label  num_channels  audio_shape  size_padding  \
1578        neutral             2         9899         19798   
2153          anger             6         9899         59394   
4219        neutral             6         9899         59394   
4216        neutral             6         9899         59394   
10400       sadness             6         9899         59394   
...             ...           ...          ...           ...   
13398      surprise             6         1024          6144   
5666        neutral             2         1024          2048   
3293        neutral             6         1024          6144   
7384            joy             6         1024          6144   
5484          anger             6         1024          6144   

                                    video_path sentiment_label  sentiment  \
1578    ../../data/test_video/dia169_utt16.mp4         neutral          1   
2153     ../../data/test_video/dia234_utt5.mp4        negative          0   
4219    ../../data/train_video/dia179_utt7.mp4         neutral          1   
4216    ../../data/train_video/dia179_utt4.mp4         neutral          1   
10400   ../../data/train_video/dia841_utt6.mp4        negative          0   
...                                        ...             ...        ...   
13398      ../../data/val_video/dia99_utt3.mp4        positive          2   
5666    ../../data/train_video/dia332_utt1.mp4         neutral          1   
3293     ../../data/train_video/dia71_utt0.mp4         neutral          1   
7384   ../../data/train_video/dia523_utt10.mp4        positive          2   
5484    ../../data/train_video/dia312_utt9.mp4        negative          0   

                                         timings  
1578            (0.30934375, 0.4124583333333333)  
